# Generated by Django 4.1.5 on 2023-01-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
